language: node_js
node_js:
    8.0
env:
    CXX=g++-4.8
cache:
  directories:
    "node_modules"
addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      g++-4.8
install:
    - npm install
script:
    - npm run build